/* header auto-generated by pidl */
#ifndef _PIDL_HEADER_krb5pac
#define _PIDL_HEADER_krb5pac
#include "include/librpc/ndr_smb.hxx"

#include "include/librpc/security.hxx"
#include "include/librpc/lsa.hxx"
#include "include/librpc/netlogon.hxx"
#include "include/librpc/samr.hxx"

namespace idl {
#ifndef _HEADER_krb5pac
#define _HEADER_krb5pac

// namespace krb5pac {

struct PAC_LOGON_NAME {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	NTTIME logon_time;
	std::u16string account_name;
	// x_ndr_vector_with_count_t<uint16> account_name;/* [charset(UTF16)] */
} ;

template <> struct x_ndr_traits_t<PAC_LOGON_NAME> {
	using has_buffers = std::false_type;
	using ndr_type = x_ndr_type_struct;
};

struct PAC_SIGNATURE_DATA {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	uint32 type;
	DATA_BLOB signature;/* [flag(LIBNDR_FLAG_REMAINING)] */
} /* [public, flag(LIBNDR_PRINT_ARRAY_HEX)] */;

template <> struct x_ndr_traits_t<PAC_SIGNATURE_DATA> {
	using has_buffers = std::false_type;
	using ndr_type = x_ndr_type_struct;
};

struct PAC_LOGON_INFO {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_buffers(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	x_ndr_off_t ndr_buffers(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	netr_SamInfo3 info3;
	std::shared_ptr<dom_sid2> res_group_dom_sid;
	samr_RidWithAttributeArray res_groups;
} ;

template <> struct x_ndr_traits_t<PAC_LOGON_INFO> {
	using has_buffers = std::true_type;
	using ndr_type = x_ndr_type_struct;
};

struct PAC_CONSTRAINED_DELEGATION {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_buffers(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	x_ndr_off_t ndr_buffers(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	lsa_String proxy_target;
	std::shared_ptr<std::vector<lsa_String>> transited_services;/* [size_is(num_transited_services)] */
	//x_ndr_unique_array_t<lsa_String, uint32> transited_services;/* [size_is(num_transited_services)] */
} ;

template <> struct x_ndr_traits_t<PAC_CONSTRAINED_DELEGATION> {
	using has_buffers = std::true_type;
	using ndr_type = x_ndr_type_struct;
};

struct PAC_LOGON_INFO_CTR {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_buffers(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	x_ndr_off_t ndr_buffers(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	std::shared_ptr<PAC_LOGON_INFO> info;
	// x_ndr_unique_ptr_t<PAC_LOGON_INFO> info;
} /* [public] */;

template <> struct x_ndr_traits_t<PAC_LOGON_INFO_CTR> {
	using has_buffers = std::true_type;
	using ndr_type = x_ndr_type_struct;
};

struct PAC_CONSTRAINED_DELEGATION_CTR {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_buffers(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	x_ndr_off_t ndr_buffers(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	std::shared_ptr<PAC_CONSTRAINED_DELEGATION> info; // x_ndr_unique_ptr_t
} /* [public] */;

template <> struct x_ndr_traits_t<PAC_CONSTRAINED_DELEGATION_CTR> {
	using has_buffers = std::true_type;
	using ndr_type = x_ndr_type_struct;
};

enum PAC_TYPE : uint32 {
	PAC_TYPE_LOGON_INFO=1,
	PAC_TYPE_SRV_CHECKSUM=6,
	PAC_TYPE_KDC_CHECKSUM=7,
	PAC_TYPE_LOGON_NAME=10,
	PAC_TYPE_CONSTRAINED_DELEGATION=11,
	PAC_TYPE_UNKNOWN_12=12,
}/* [v1_enum, public] */;

template <> struct x_ndr_traits_t<PAC_TYPE> {
	using has_buffers = std::false_type;
	using ndr_type = x_ndr_type_enum;
	using ndr_base_type = uint32;
	static const std::array<std::pair<uint32, const char *>, 6> value_name_map;
};

template <> inline x_ndr_off_t x_ndr_scalars<PAC_TYPE>(const PAC_TYPE &__val, x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level)
{
	X_ASSERT(__level == X_NDR_SWITCH_NONE);
	return x_ndr_push_uint32(__val, __ndr, __bpos, __epos, __flags);
}

template <> inline x_ndr_off_t x_ndr_scalars<PAC_TYPE>(PAC_TYPE &__val, x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level)
{
	uint32_t v;
	X_NDR_SCALARS(v, __ndr, __bpos, __epos, __flags, __level);
	__val = PAC_TYPE(v);
	return __bpos;
}


struct DATA_BLOB_REM {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	DATA_BLOB remaining;/* [flag(LIBNDR_FLAG_REMAINING)] */
} ;

template <> struct x_ndr_traits_t<DATA_BLOB_REM> {
	using has_buffers = std::false_type;
	using ndr_type = x_ndr_type_struct;
};

union PAC_INFO
{
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	x_ndr_off_t ndr_buffers(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_buffers(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	PAC_INFO(x_ndr_switch_t __level) { __init(__level); }
	~PAC_INFO() { }
	void __init(x_ndr_switch_t __level);
	void __init(x_ndr_switch_t __level, const PAC_INFO &__other);
	void __uninit(x_ndr_switch_t __level);
	PAC_LOGON_INFO_CTR logon_info;/* [subcontext(0xFFFFFC01), case(PAC_TYPE_LOGON_INFO)] */
	// x_ndr_subndr_t<PAC_LOGON_INFO_CTR> logon_info;/* [subcontext(0xFFFFFC01), case(PAC_TYPE_LOGON_INFO)] */
	PAC_SIGNATURE_DATA srv_cksum;/* [case(PAC_TYPE_SRV_CHECKSUM)] */
	PAC_SIGNATURE_DATA kdc_cksum;/* [case(PAC_TYPE_KDC_CHECKSUM)] */
	PAC_LOGON_NAME logon_name;/* [case(PAC_TYPE_LOGON_NAME)] */
	PAC_CONSTRAINED_DELEGATION_CTR constrained_delegation;/* [subcontext(0xFFFFFC01), case(PAC_TYPE_CONSTRAINED_DELEGATION)] */
	// x_ndr_subndr_t<PAC_CONSTRAINED_DELEGATION_CTR> constrained_delegation;/* [subcontext(0xFFFFFC01), case(PAC_TYPE_CONSTRAINED_DELEGATION)] */
	DATA_BLOB_REM unknown;/* [subcontext(0), default] */
} /* [gensize, nodiscriminant, public] */;

template <> struct x_ndr_traits_t<PAC_INFO> {
	using has_buffers = std::false_type;
	using ndr_type = x_ndr_type_union;
};


struct PAC_BUFFER {
	~PAC_BUFFER();
#if 0
	PAC_BUFFER();
	PAC_BUFFER(const PAC_BUFFER& other);
	PAC_BUFFER &operator=(const PAC_BUFFER& other);
#endif
	void set_type(PAC_TYPE v);
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_buffers(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	x_ndr_off_t ndr_buffers(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	PAC_TYPE type;
	std::shared_ptr<PAC_INFO> info;/* [relative, switch_is(type), flag(LIBNDR_FLAG_ALIGN8)] */
} /* [noprint, nopull, public, nopush] */;

template <> struct x_ndr_traits_t<PAC_BUFFER> {
	using has_buffers = std::true_type;
	using ndr_type = x_ndr_type_struct;
};

struct PAC_DATA {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_buffers(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	x_ndr_off_t ndr_buffers(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	uint32 version;
	std::vector<PAC_BUFFER> buffers; // x_ndr_vector_with_count_t
} /* [public] */;

template <> struct x_ndr_traits_t<PAC_DATA> {
	using has_buffers = std::true_type;
	using ndr_type = x_ndr_type_struct;
};

struct PAC_BUFFER_RAW {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_buffers(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	x_ndr_off_t ndr_buffers(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	PAC_TYPE type;
	std::shared_ptr<DATA_BLOB> info;/* [relative, flag(LIBNDR_FLAG_ALIGN8)] */
} /* [public] */;

template <> struct x_ndr_traits_t<PAC_BUFFER_RAW> {
	using has_buffers = std::true_type;
	using ndr_type = x_ndr_type_struct;
};

struct PAC_DATA_RAW {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_buffers(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	x_ndr_off_t ndr_buffers(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	uint32 version;
	std::vector<PAC_BUFFER_RAW> buffers; // x_ndr_vector_with_count_t
} /* [public] */;

template <> struct x_ndr_traits_t<PAC_DATA_RAW> {
	using has_buffers = std::true_type;
	using ndr_type = x_ndr_type_struct;
};
const int NETLOGON_GENERIC_KRB5_PAC_VALIDATE = 3;

struct PAC_Validate {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	uint32 ChecksumLength;
	int32 SignatureType;
	uint32 SignatureLength;
	DATA_BLOB ChecksumAndSignature;/* [flag(LIBNDR_FLAG_REMAINING)] */
} /* [public] */;

template <> struct x_ndr_traits_t<PAC_Validate> {
	using has_buffers = std::false_type;
	using ndr_type = x_ndr_type_struct;
};

struct netsamlogoncache_entry {
	x_ndr_off_t ndr_scalars(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_buffers(x_ndr_push_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level) const;
	x_ndr_off_t ndr_scalars(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	x_ndr_off_t ndr_buffers(x_ndr_pull_t &__ndr, x_ndr_off_t __bpos, x_ndr_off_t __epos, uint32_t __flags, x_ndr_switch_t __level);
	void ostr(x_ndr_ostr_t &__ndr, uint32_t __flags, x_ndr_switch_t __level) const;
	time_t timestamp;
	netr_SamInfo3 info3;
} /* [public] */;

template <> struct x_ndr_traits_t<netsamlogoncache_entry> {
	using has_buffers = std::true_type;
	using ndr_type = x_ndr_type_struct;
};
// }
#endif /* _HEADER_krb5pac */
} /* namespace idl */

#endif /* _PIDL_HEADER_krb5pac */

