
#ifndef __smb2__hxx__
#define __smb2__hxx__

#ifndef __cplusplus
#error "Must be c++"
#endif

extern "C" {
#include "samba/libcli/smb/smb_constants.h"
#include "samba/libcli/smb/smb2_constants.h"
#include "samba/libcli/util/ntstatus.h"
}

#define X_SMB2_OP_ENUM \
	X_SMB2_OP_DECL(NEGPROT) \
	X_SMB2_OP_DECL(SESSSETUP) \
	X_SMB2_OP_DECL(LOGOFF) \
	X_SMB2_OP_DECL(TCON) \
	X_SMB2_OP_DECL(TDIS) \
	X_SMB2_OP_DECL(CREATE) \
	X_SMB2_OP_DECL(CLOSE) \
	X_SMB2_OP_DECL(FLUSH) \
	X_SMB2_OP_DECL(READ) \
	X_SMB2_OP_DECL(WRITE) \
	X_SMB2_OP_DECL(LOCK) \
	X_SMB2_OP_DECL(IOCTL) \
	X_SMB2_OP_DECL(CANCEL) \
	X_SMB2_OP_DECL(KEEPALIVE) \
	X_SMB2_OP_DECL(QUERY_DIRECTORY) \
	X_SMB2_OP_DECL(NOTIFY) \
	X_SMB2_OP_DECL(GETINFO) \
	X_SMB2_OP_DECL(SETINFO) \
	X_SMB2_OP_DECL(BREAK) \

enum {
        SMB2_FILE_INFO_FILE_DIRECTORY_INFORMATION = 1,
        SMB2_FILE_INFO_FILE_FULL_DIRECTORY_INFORMATION = 2,
        SMB2_FILE_INFO_FILE_BOTH_DIR_INFORMATION = 3,
        SMB2_FILE_INFO_FILE_BASIC_INFORMATION = 4,
        SMB2_FILE_INFO_FILE_STANDARD_INFORMATION = 5,
        SMB2_FILE_INFO_FILE_INTERNAL_INFORMATION = 6,
        SMB2_FILE_INFO_FILE_EA_INFORMATION = 7,
        SMB2_FILE_INFO_FILE_ACCESS_INFORMATION = 8,
        SMB2_FILE_INFO_FILE_NAME_INFORMATION = 9,
        SMB2_FILE_INFO_FILE_RENAME_INFORMATION = 10,
        SMB2_FILE_INFO_FILE_NAMES_INFORMATION = 12,
        SMB2_FILE_INFO_FILE_DISPOSITION_INFORMATION = 13,
        SMB2_FILE_INFO_FILE_POSITION_INFORMATION = 14,
        SMB2_FILE_INFO_FILE_MODE_INFORMATION = 16,
        SMB2_FILE_INFO_FILE_ALIGNMENT_INFORMATION = 17,
        SMB2_FILE_INFO_FILE_ALL_INFORMATION = 18,
        SMB2_FILE_INFO_FILE_ALLOCATION_INFORMATION = 19,
        SMB2_FILE_INFO_FILE_END_OF_FILE_INFORMATION = 20,
        SMB2_FILE_INFO_FILE_STREAM_INFORMATION = 22,
        SMB2_FILE_INFO_FILE_COMPRESSION_INFORMATION = 28,
        SMB2_FILE_INFO_FILE_NETWORK_OPEN_INFORMATION = 34,
        SMB2_FILE_INFO_FILE_ATTRIBUTE_TAG_INFORMATION = 35,
        SMB2_FILE_INFO_FILE_ID_BOTH_DIR_INFORMATION = 37,
        SMB2_FILE_INFO_FILE_ID_FULL_DIR_INFORMATION = 38,
        SMB2_FILE_INFO_FILE_VALID_DATA_LENGTH_INFORMATION = 39,
};

enum {
	SMB2_FILE_INFO_FS_SIZE_INFORMATION = 3,
};

struct x_smb2_preauth_t
{
	std::array<char, 64> data{};
	void update(const void *data, size_t length);
};



#endif /* __smb2__hxx__ */

